// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	image "image"

	kernels "github.com/drew138/go-graphics/filters/kernels"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// TransformImage provides a mock function with given fields: _a0, kernel
func (_m *Service) TransformImage(_a0 image.Image, kernel kernels.Kernel) ([]byte, error) {
	ret := _m.Called(_a0, kernel)

	if len(ret) == 0 {
		panic("no return value specified for TransformImage")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(image.Image, kernels.Kernel) ([]byte, error)); ok {
		return rf(_a0, kernel)
	}
	if rf, ok := ret.Get(0).(func(image.Image, kernels.Kernel) []byte); ok {
		r0 = rf(_a0, kernel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(image.Image, kernels.Kernel) error); ok {
		r1 = rf(_a0, kernel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
